; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_dir = D:/shm_build

[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	knolleary/PubSubClient @ ^2.8
	tzapu/WiFiManager @ ^2.0
	bblanchon/ArduinoJson @ ^7.3
upload_speed = 921600
monitor_speed = 115200
platform_packages = platformio/tool-mklittlefs@1.203.210628

[env:node_01]
build_flags = -DNODE_ID='"node_01"'

[env:node_02]
build_flags = -DNODE_ID='"node_02"'
